---
title: "Homework - Week 10"
---

*Instructions: Show your work for full credit. Submit your scanned homework on canvas.*

::: {.callout-warning title="Problem 1"}
Suppose that $X$ and $Y$ have a discrete joint distribution
for which the joint pmf is defined as follows:

$$
f(x,y) =
    \begin{cases}
      \frac{1}{30}(x+y) & \text{for }\ x=0,2 \text{and}\ y=0,1,2,3,4.\\
      0 & \text{otherwise}
    \end{cases}
$$


a. Determine the marginal pmfs of \( X \) and \( Y \).
b. Are \( X \) and \( Y \) independent?
:::

::: {.callout-warning title="Problem 2"}
Imagine that the joint pdf of \(X \) and \(Y\) is as follows:

$$
f(x,y) =
    \begin{cases}
      4xe^{-y} & \text{for }\ 0 \leq x \leq \sqrt{\frac{1}{2}} \text{and}\ 0 \leq y \leq \infty.\\
      0 & \text{otherwise}
    \end{cases}
$$

Are \(X\) and \(Y\) independent?
:::

::: {.callout-warning title="Problem 3"}
Take a point \( (X, Y )\) picked arbitrarily from circle \(S\), characterized by:
$$S=\{(x,y):x^2+y^2 \leq 1\}$$
If $f(x,y) = kx^2y^2$, verify that \(X\) and \(Y\) have the same marginal pdf:

$$
f(x) =
    \begin{cases}
      \frac{2kx^2(1-x^2)^{\frac{3}{2}}}{3} & \text{if }\ -1 \leq x \leq 1.\\
      0 & \text{otherwise}
    \end{cases}
$$
:::

::: {.callout-warning title="Problem 4"}
Suppose that a point $(X,Y)$ is chosen at random from the following disk
  $S$:
$$S=\{(x,y):(x-1)^2+(y+2)^2 \leq 16\}.$$
Determine:

a. the conditional pdf of $Y$ for every given value of $X$.
b. $\mathbb{P}(Y>0 \mid X=3)$.
:::

::: {.callout-warning title="Problem 5"}
Let $Y$ be the rate (calls per hour) at which calls arrive at a
  switchboard. Let $X$ be the number of calls during a two-hour period. Suppose
  that the marginal pdf of $Y$ is

$$
f_2(y)= \begin{cases}e^{-y} & \text { if } y>0 \\ 0 & \text { otherwise }\end{cases}
$$

and that the conditional pmf of $X$ given $Y=y$ is

$$
g_1(x \mid y)= \begin{cases}\frac{(2 y)^x}{x!} e^{-2 y} & \text { if } x=0,1, \ldots, \\ 0 & \text { otherwise. }\end{cases}
$$


(Hint: this is a *mixed* joint distribution.)


a. Find the marginal pmf of $X$. (You may use the formula
  $\int_0^{\infty} y^k e^{-y} d y=k!$)

b. Find the conditional pdf $g_2(y \mid 0)$ of $Y$ given $X=0$.
c. Find the conditional pdf $g_2(y \mid 1)$ of $Y$ given $X=1$.
d. For what values of $y$ is $g_2(y \mid 1)>g_2(y \mid 0)$ ? Does this
  agree with the intuition that the more calls you see, the higher you should
  think the rate is?
:::

::: {.callout-warning title="Problem 6"}
Suppose $f(x,y) = e^{-x} \cdot \mathbf{1}_{0\le y \le x <\infty}$. Find the conditional pdf $f_{Y|X}(y|x)$.
:::

::: {.callout-warning title="Problem 7"}
Suppose $X \sim \text{Beta}(a,b)$ for constants $a,b >0$, and
  $Y| X=x \sim \text{Binomial}(N,x)$ where $N$ is some fixed constant.
  Find the conditional pdf of $X|Y=y$ for some $y\in 0,...,N$. (Hint: you've
  already seen a simpler version of this in lecture.)
:::
